### PR TITLE
Remove lodash.deepClone in favor of Object.assign

### PR DESCRIPTION
**Pull request by gm112**
Removes a dependency in favor of a native equivalent!

### CODE REVIEW

**Comment by Pridestalkerr** [comment]
`Object.assign()` creates a shallow copy as opposed to `lodash.cloneDeep()`.
They would only be equivalent if all keys inside those objects are primitives, otherwise everything else (such as nested objects) will have the same reference.

This change may actually work, but really need to make sure that mutations arent performed on the cloned objects.

**Comment by mcampa** [comment]
seems reasonable, thanks

**Comment by mcampa** [comment]
Ahh, thanks for letting me know @lawandothman. I probably published to npm without running a build first. I need to setup a Github Action that publishes the build to npm to prevent this from happening in the future.

I just published 2.1.2 to fix the issue, you can use that version. Please let me know if you find any other issue.

**Comment by lawandothman** [comment]
Yep that fixed the build @mcampa - thank you 🙂

**Pull request merged**
